server:
  port: 8081

spring:
  application:
    name: sdg-smart-discount-generator
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Gemini configuration for tool calling
gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyDQD0W7maSXEkvcOX0Hicp6FoqqyteTZZ4}
  base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# Legacy Algolia config (kept for backward compatibility)
algolia:
  application-id: ${ALGOLIA_APPLICATION_ID:D5NLZGUAN7}
  admin-api-key: ${ALGOLIA_ADMIN_API_KEY:f563ed99dff0f7ccb8c2b78e681376be}
  search-api-key: ${ALGOLIA_SEARCH_API_KEY:your_algolia_search_key}
  indexes:
    products: sdg_products
    user-events: sdg_user_events
    discount-templates: sdg_discount_templates

# MCP Server Configuration
mcp:
  server:
    name: algolia-smart-discount-generator
    version: 1.0.0
    description: Smart Discount Generator with Algolia integration and AI-powered discount generation
    url: ${MCP_SERVER_URL:http://localhost:3000}
    enabled: ${MCP_ENABLED:true}
    timeout-seconds: 10
    retry-attempts: 2

# Discount Configuration
discount:
  default-expiry-minutes: 30
  max-discount-percentage: 50
  min-profit-margin: 0.10

logging:
  level:
    com.dev.challenge.sdg: DEBUG
    org.springframework.web: INFO
