server:
  port: 8080

spring:
  application:
    name: smart-discount-generator
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Algolia Configuration
algolia:
  application-id: ${ALGOLIA_APPLICATION_ID:your_algolia_app_id}
  admin-api-key: ${ALGOLIA_ADMIN_API_KEY:your_algolia_admin_key}
  search-api-key: ${ALGOLIA_SEARCH_API_KEY:your_algolia_search_key}
  indexes:
    products: sdg_products
    user-events: sdg_user_events
    discount-templates: sdg_discount_templates

# Gemini AI Configuration
gemini:
  api-key: ${GEMINI_API_KEY:your_gemini_api_key}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
  model: gemini-pro

# MCP Server Configuration
mcp:
  server:
    name: algolia-discount-mcp
    version: 1.0.0
    description: Smart Discount Generator MCP Server for Algolia integration

# Discount Configuration
discount:
  default-expiry-minutes: 30
  max-discount-percentage: 50
  min-profit-margin: 0.10

logging:
  level:
    com.dev.challenge.sdg: DEBUG
    org.springframework.web: INFO
