server:
  port: 8080

spring:
  application:
    name: sdg-api-gateway
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# MCP Server connection configuration
mcp:
  server:
    base-url: http://localhost:8081
    timeout: 30000
    name: algolia-discount-mcp
    version: 1.0.0
    description: Smart Discount Generator MCP Server for Algolia integration

# Gemini configuration for tool calling
gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyDQD0W7maSXEkvcOX0Hicp6FoqqyteTZZ4}
  model: gemini-pro
  base-url: https://generativelanguage.googleapis.com/v1beta

# Legacy Algolia config (kept for backward compatibility)
algolia:
  application-id: ${ALGOLIA_APPLICATION_ID:your_algolia_app_id}
  admin-api-key: ${ALGOLIA_ADMIN_API_KEY:f563ed99dff0f7ccb8c2b78e681376be}
  search-api-key: ${ALGOLIA_SEARCH_API_KEY:your_algolia_search_key}
  indexes:
    products: sdg_products
    user-events: sdg_user_events
    discount-templates: sdg_discount_templates

# Discount Configuration
discount:
  default-expiry-minutes: 30
  max-discount-percentage: 50
  min-profit-margin: 0.10

logging:
  level:
    com.dev.challenge.sdg: DEBUG
    org.springframework.web: INFO
